import { createApp } from 'vue'
import 'comz/dist/style.css'
import '@comz/style'

// import Comp from './src/button.vue'
// import Comp from './src/card.vue'
// import Comp from './src/grid.vue'
// import Comp from './src/icon.vue'
// import Comp from './src/modal.vue'
// import Comp from './src/alert.vue'
// import Comp from './src/toast.vue'
// import Comp from './src/input.vue'
// import Comp from './src/textarea.vue'
// import Comp from './src/radio.vue'
// import Comp from './src/checkbox.vue'
// import Comp from './src/select.vue'
// import Comp from './src/space.vue'
// import Comp from './src/form.vue'
// import Comp from './src/panel.vue'
// import Comp from './src/switch.vue'
// import Comp from './src/ruler.vue'
import Comp from './src/tooltip.vue'

createApp(Comp).mount('#app')